language: cpp

cache: ccache

matrix:
  include:
  - os: linux
    dist: xenial
    script:
    - cd .. && git clone https://github.com/UIUC-PPL/charm && cd charm && ./build AMPI netlrts-linux-x86_64 -j3 --with-production -g
    - cd ../hdf5-ampi && CHARMRUN_OPTS=++local make -f Makefile.ampi
    - make test
